name: springboot-webservice # workflow 의 이름 지정

on:
  workflow_dispatch:

jobs:
  build:
    run-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        whith:
          java-version: 1.8

      - name: Greant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash